// Runs before each test file's imports, so `config` is parsed from these values (never from a real .env).
Object.assign(process.env, {
  NODE_ENV: 'test',
  MONGODB_URI: 'mongodb://tests-connect-explicitly-to-the-in-memory-server',
  MONGODB_DB_NAME: 'unused_in_tests',
  JWT_SECRET: 'test-only-secret-test-only-secret-0123456789',
  COOKIE_SECURE: 'false',
  BCRYPT_ROUNDS: '4',
  RATE_LIMIT_ENABLED: 'false',
  MAX_UPLOAD_MB: '1',
  LOG_LEVEL: 'silent',
  ADMIN_EMAIL: '',
  ADMIN_PASSWORD: '',
  GEMINI_API_KEY: '',
  // AI runs against the scriptable mock provider; bag-of-words mock embeddings need lower thresholds.
  AI_PROVIDER: 'mock',
  AI_MODEL_PRIMARY: 'mock-primary',
  AI_MODEL_FALLBACKS: 'mock-fallback',
  AI_MODEL_LIGHT: 'mock-light',
  AI_MODEL_LIGHT_FALLBACKS: '',
  AI_EMBEDDING_MODEL: 'mock-embedding',
  VECTOR_SEARCH_ENABLED: 'false',
  RETRIEVAL_STRONG_SCORE: '0.35',
  RETRIEVAL_MIN_SCORE: '0.2',
  TUTOR_JUDGE_SAMPLE_RATE: '0',
  QUIZ_JUDGE_SAMPLE_RATE: '0',
});
